version: '3.8'
services:
  hf_db_server:
    container_name: hf_psql
    image: nziswiler/psql
    restart: always
    environment:
      POSTGRES_USER: vmadmin
      POSTGRES_PASSWORD: sml12345
      POSTGRES_DB: hf_db
    ports:
      - "5432:5432"
  hf_db_frontend:
    container_name: hf_padm
    image: nziswiler/padm
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: nino.marco.ziswiler@iet-gibb.ch
      PGADMIN_DEFAULT_PASSWORD: sml12345
    ports:
      - "11013:80"
